[package]
name = "twitch-cli"
version = "0.1.0"
edition = "2024"


[dependencies]
twitch-irc = "5"
tokio = { version = "1", features = ["full"] }
dotenv_codegen = "0.15.0"
dotenv = "0.15.0"

[profile.release]
panic = 'abort'


